name: "@Mobile • Build App"
run-name: "@Mobile • Build App triggered by ${{ inputs.login || github.actor }} ${{ format('on ref {0}', github.ref_name) }}"

on:
  push:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name != 'develop' && github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  build-mobile-app-android:
    name: "Build Ledger Live Mobile (Android)"
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max-old-space-size=7168"
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.sha }}
      - name: Setup git user
        uses: LedgerHQ/ledger-live/tools/actions/composites/setup-git-user@develop
      - name: install proto 
        run: curl -fsSL https://moonrepo.dev/install/proto.sh | bash -s -- --yes
      - name: proto install
        run: proto use
      - name: install dependencies
        run: pnpm i --filter="live-mobile..." --filter="ledger-live" --no-frozen-lockfile --unsafe-perm
      - uses: LedgerHQ/ledger-live/tools/actions/get-package-infos@develop
        id: version
        with:
          path: ${{ github.workspace }}/apps/ledger-live-mobile
      - name: set beta name
        uses: LedgerHQ/ledger-live/tools/actions/change-product-name@develop
        with:
          path: ${{ github.workspace }}/apps/ledger-live-mobile
      - name: Get short SHA
        id: slug
        run: echo "sha8=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: make local version
        env:
          VERSION: ${{ steps.version.outputs.clean }}-sha.${{ steps.slug.outputs.sha8 }}
        run: cd apps/ledger-live-mobile && npm version $VERSION
      - name: build the app
        env:
          ANDROID_KEYSTORE_PASS: staging
          ANDROID_KEY_ALIAS: staging
          ANDROID_KEY_PASS: staging
          NODE_OPTIONS: "--max-old-space-size=7168"
          ANDROID_KEYSTORE_FILE: ${{ github.workspace }}/apps/ledger-live-mobile/android/app/staging.kstr
        run: pnpm build-ci:llm:android --api="http://127.0.0.1:${{ steps.caches.outputs.port }}" --token="${{ secrets.TURBOREPO_SERVER_TOKEN }}" --team="foo"
      - uses: LedgerHQ/ledger-live/tools/actions/get-package-infos@develop
        id: post-version
        with:
          path: ${{ github.workspace }}/apps/ledger-live-mobile
      - name: upload Android app
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.post-version.outputs.version }}-release
          path: ${{ github.workspace }}/apps/ledger-live-mobile/android/app/build/outputs/apk/stagingRelease